name: CI/CD Pipeline for Node.js App

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REPO_URI }} .
        docker nodejsapp:latest ${{ secrets.ECR_REPO_URI }}:latest

    - name: Log in to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_REPO_URI }}:latest

    - name: Deploy to AWS ECS Fargate
      run: |
        # You will need to use AWS CLI commands to deploy the image to ECS Fargate
        aws ecs update-service \
          --cluster your-cluster-name \
          --service your-service-name \
          --force-new-deployment \
          --region ${{ secrets.AWS_REGION }}
